table tbPedidoDet
	lineageTag: c4c63a28-8b56-4815-978a-706910c6f31f

	column NroPedido
		dataType: int64
		formatString: 0
		lineageTag: 5d27eeaf-99a8-4d6a-bcbf-1c79849d12af
		summarizeBy: none
		sourceColumn: NroPedido

		annotation SummarizationSetBy = Automatic

	column CodProduto
		dataType: int64
		formatString: 0
		lineageTag: 5ab83c8d-8dba-4d9f-9726-72c3e3ba14e1
		summarizeBy: none
		sourceColumn: CodProduto

		annotation SummarizationSetBy = Automatic

	column Quantidade
		dataType: int64
		formatString: 0
		lineageTag: 386f49a3-5307-4fc7-b27c-6ec9f820ab4e
		summarizeBy: sum
		sourceColumn: Quantidade

		annotation SummarizationSetBy = Automatic

	column ValorUnitario
		dataType: int64
		formatString: 0
		lineageTag: b645b4a0-1fc9-4c40-a07f-7298c6a78275
		summarizeBy: sum
		sourceColumn: ValorUnitario

		annotation SummarizationSetBy = Automatic

	column ValorDescontoItem
		dataType: double
		lineageTag: 3ff5392a-1ffe-4909-a931-3b29e15df8b1
		summarizeBy: sum
		sourceColumn: ValorDescontoItem

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ValorTotalItem = (tbPedidoDet[ValorUnitario] * tbPedidoDet[Quantidade]) - tbPedidoDet[ValorDescontoItem]
		dataType: double
		lineageTag: 2e88f43e-283f-46d1-a870-81894dfe5d1c
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition tbPedidoDet = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power BI EBAC\M2\M2 - tbPedidoDet.csv"),[Delimiter=";", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"NroPedido", Int64.Type}, {"CodProduto", Int64.Type}, {"Quantidade", Int64.Type}, {"ValorUnitario", Int64.Type}, {"ValorDescontoItem", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

